#paths:
stage: "tartanair"
image_size: [480, 640]
root: "/zihao/datasets/"
traj: ["abandonedfactory"]
savename: "TartanAir"

stereo: True
model_path: ["models/100/85001_RAFTCov.pth"]
length: 100

training_mode: "cov"
seed: 2568
sum_freq: 100
#gaussian:
dim: 64
dropout: 0.

num_heads: 4
mixtures: 8
gru_iters: 1
#paths:

img_path: "/zihao/datasets/abandonedfactory/Data/P000/"
depth_path: "/zihao/datasets/abandonedfactory/Data/P000/depth_left/"
result_path: "results/stereo_100/"
